// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contact from "./routes/contact.tsx";
import * as $downloads from "./routes/downloads.tsx";
import * as $faq from "./routes/faq.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $news from "./routes/news.tsx";
import * as $news_id_ from "./routes/news/[id].tsx";
import * as $products from "./routes/products.tsx";
import * as $project_overview from "./routes/project-overview.tsx";
import * as $research from "./routes/research.tsx";
import * as $sitemap from "./routes/sitemap.tsx";
import * as $training from "./routes/training.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FAQSection from "./islands/FAQSection.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contact.tsx": $contact,
    "./routes/downloads.tsx": $downloads,
    "./routes/faq.tsx": $faq,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/news.tsx": $news,
    "./routes/news/[id].tsx": $news_id_,
    "./routes/products.tsx": $products,
    "./routes/project-overview.tsx": $project_overview,
    "./routes/research.tsx": $research,
    "./routes/sitemap.tsx": $sitemap,
    "./routes/training.tsx": $training,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/FAQSection.tsx": $FAQSection,
    "./islands/MobileNav.tsx": $MobileNav,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
